[project]
name = "rezonance"
version = "0.1.0"
description = "Monophonic and polyphonic playground"
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    'ipython',
    'numpy==2.3.*',
    'scikit-learn==1.8.*',
    'torch==2.10.*',
    'pandas==3.0.*',
    'torchaudio==2.10.*',
    'torchcodec==0.10.*',
    'matplotlib',
    'sounddevice',
]
[tool.uv.sources]
torch = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchaudio = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv]
package = true

[tool.ruff]
exclude = [".venv"]
line-length = 70
indent-width = 4
