[project]
name = "rezonance"
version = "0.1.0"
description = "Monophonic and polyphonic playground"
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    'ipython',
    'numpy==2.3.*',
    'scikit-learn==1.8.*',
    'torch==2.10.*',
    'pandas==3.0.*',
    'torchaudio==2.10.*',
    'torchcodec==0.10.*',
    'matplotlib',
    'sounddevice',
]

[tool.uv]
package = true

[tool.ruff]
exclude = [".venv"]
line-length = 70
indent-width = 4
